theme = "ayu_evolve"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
h = ":toggle-option lsp.display-inlay-hints"
O = "jump_backward"
N = "jump_forward"

[editor.lsp]
display-messages = true
display-inlay-hints = true
inlay-hints-max-length = 20

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
